### ISSUE TITLE
2.8.0-12.1 cobbler sync Exception occured: <type 'exceptions.KeyError'> when rendering DHCP files

### ISSUE THREAD

**Issue by garutilorenzo** [cobbler/cobbler#1735]
On a fresh install of cobbler 2.8 on a CentOs 7.2 machine, when we have a system with two bridged networks adapter (br0 and br1) we receive a KeyError Exception:

```
rendering DHCP files
Exception occured: <type 'exceptions.KeyError'>
Exception value: 'br0'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 82, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.sync(self.options.get("verbose",False),logger=self.logger)
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 763, in sync
    return sync.run()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 122, in run
    self.write_dhcp()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 208, in write_dhcp
    self.dhcp.write_dhcp_file()
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_isc.py", line 106, in write_dhcp_file
    if len(ding[system.name][interface["interface_master"]]) == 0:

!!! TASK FAILED !!! 
```
If we delete the second bridged interface (br1), everything works fine.
br0 is the master interface of physical interface eth0  and br1 is the master interface of physical interface eth1.
On a 2.6 cobbler install everything works fine.

The content of the interface variable is:

`{'ipv6_address': u'', 'interface_type': 'bridge_slave', 'static': False, 'cnames': [], 'owner': 'test', 'enable_gpxe': False, 'gateway': u'', 'management': False, 'interface_master': 'br1', 'hostname': u'', 'filename': '/pxelinux.0', 'bridge_opts': u'', 'mac_address': 'D8:9D:67:XX:XX:XX', 'ipv6_prefix': u'', 'netboot_enabled': True, 'distro': {'comment': u'', 'kernel': '/var/www/cobbler/ks_mirror/CentOS-7-x86_64/images/pxeboot/vmlinuz', 'uid': 'XXXXXXXXXXXXXXXXXXXX', 'kernel_options_post': {}, 'redhat_management_key': '<<inherit>>', 'kernel_options': {}, 'redhat_management_server': '<<inherit>>', 'initrd': '/var/www/cobbler/ks_mirror/CentOS-7-x86_64/images/pxeboot/initrd.img', 'mtime': 1468497870.014401, 'template_files': {}, 'ks_meta': {'tree': 'http://@@http_server@@/cblr/links/CentOS-7-x86_64'}, 'boot_files': {}, 'breed': 'redhat', 'os_version': 'rhel7', 'mgmt_classes': [], 'fetchable_files': {}, 'tree_build_time': 0, 'arch': 'x86_64', 'name': 'CentOS-7-x86_64', 'owners': ['admin'], 'ctime': 1468497862.73862, 'source_repos': [['http://@@http_server@@/cobbler/ks_mirror/config/CentOS-7-x86_64-0.repo', 'http://@@http_server@@/cobbler/ks_mirror/CentOS-7-x86_64']], 'depth': 0}, 'virt_bridge': 'xenbr0', 'netmask': u'', 'bonding_opts': u'', 'ipv6_mtu': u'', 'ip_address': u'', 'dhcp_tag': u'', 'name': 'generic1', 'static_routes': [], 'ipv6_static_routes': [], 'if_gateway': u'', 'dns_name': u'', 'mtu': u'', 'connected_mode': False, 'ipv6_secondaries': [], 'next_server': '192.168.66.2', 'ipv6_default_gateway': u''}`

and the content of the ding variable is:

`{'test': {'br0': ['D8:9D:67:XX:XX:XX']}`

Cobbler is configured to manage dhcp and also dns:

[...]
manage_dhcp: 1
...
manage_dns: 1
[...]

this is te content of modules.conf:

[...]
[dns]
module = manage_bind
...
[dhcp]
module = manage_isc
[...]

**Comment by garutilorenzo** [comment]
with [this](https://github.com/cobbler/cobbler/commit/5724afee227ee556693fbbba6ac1cd476108638f#diff-cc6654134521a72720f2b7fbf31f0ed9) version of manage_isc.py everything works fine.

**Comment by jmaas** [comment]
Backported @opoplawski fix to release28.
This issue should be fixed in the next release: 2.8.1

**Comment by opoplawski** [comment]
You overwrote the backport with commit 73960cf2eb203d0dd5d4404bbfd67a3359b480a6 so I'm back to seeing this error.

**Comment by hendrahendra** [comment]
Why was the fix removed from 2.8.2? Without the "else" statement, the error is back again.

```
                    if not system.name in ding:
                        ding[system.name] = {interface["interface_master"]: []}
                    else:
                        ding[system.name][interface["interface_master"]] = []

```

**Comment by jsosic** [comment]
@hendrahendra `else` block is needed in `cobbler-2.8.1-2.el7.x86_64` which is the version distributed from EPEL at time of writing this post...

**Comment by Sispheor** [comment]
Hi guys, I've installed the last epel version and I confirm the issue.
I've edited the python file manually but I still have the issue during a cobbler sync
```
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 82, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.sync(self.options.get("verbose",False),logger=self.logger)
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 763, in sync
    return sync.run()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 122, in run
    self.write_dhcp()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 208, in write_dhcp
    self.dhcp.write_dhcp_file()
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_isc.py", line 171, in write_dhcp_file
    dhcp_tag = blended_system["dhcp_tag"]

!!! TASK FAILED !!!
```

**Comment by Sispheor** [comment]
And seems to appears when the system is not attached to a profile.

**Comment by Sispheor** [comment]
I fixed the issue by adding "default" to the dhcp tag of all machines declared without attached profile.

**Comment by elfchief** [comment]
Isn't the dhcp tag issue a different issue?

I definitely confirm that the original issue (multiple bond interfaces resulting in a `KeyError` in `ding[system.name][interface["interface_master"]]`) has returned with commit 211222357616d8fc3e26006f71ac42d84d15bb92 .

This is really obnoxious, I would appreciate if you would fix!

**Comment by FlorianneRaven** [comment]
I have the same error and can't deploy bond

**Comment by AJxx** [comment]
Appreciate if someone can guide me to the fix.

Cobbler Version :  2.8.0

# Add Server
cobbler system add --mac 00:50:56:00:01:86 --name serverx --profile rhel74-x86_64 --hostname serverx.abc.local --interface bond0  --kickstart=/var/lib/cobbler/kickstarts/OLD/serverx.ks --dns-name=serverx.abc.local

# Bond0
cobbler system edit --interface-type=bond --bonding-opts=miimon=100 mode=1  --static 1 --ip-address 10.10.10.125 --subnet 255.255.255.0 --if-gateway 10.10.10.1 --name-servers 10.10.10.5
cobbler system edit --name=serverx --interface eth0-mgmt --mac 00:50:56:00:01:86 --interface-type=bond_slave --interface-master bond0
cobbler system edit --name=serverx --interface eth1-mgmt --mac 00:50:56:9a:25:7a --interface-type=bond_slave --interface-master bond0

# Bond1 with VLAN Tag
cobbler system edit --name=serverx --interface bond1.11 --interface-type=bond --bonding-opts=miimon=100 mode=1  --static 1 --ip-address 20.20.20.125 --subnet 255.255.255.0
cobbler system edit --name=serverx --interface eth2-front --mac 00:50:56:9a:59:7b --interface-type=bond_slave --interface-master bond1.11
cobbler system edit --name=serverx --interface eth3-front --mac 00:50:56:9a:4b:fa --interface-type=bond_slave --interface-master bond1.11

# cobbler sync
rendering DHCP files
Exception occured: <type 'exceptions.KeyError'>
Exception value: 'bond1.11'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 82, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.sync(self.options.get("verbose",False),logger=self.logger)
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 763, in sync
    return sync.run()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 122, in run
    self.write_dhcp()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 208, in write_dhcp
    self.dhcp.write_dhcp_file()
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_isc.py", line 106, in write_dhcp_file
    if len(ding[system.name][interface["interface_master"]]) == 0:

!!! TASK FAILED !!!

# Added the tweaks mentioned by @hendrahendra 

[root@servery modules]# diff manage_isc.py manage_isc.py_bkp_20180316
105,108d104
<                     if not system.name in ding:
<                         ding[system.name] = {interface["interface_master"]: []}
<                     else:
<                         ding[system.name][interface["interface_master"]] = []
[root@servery modules]#


# cobbler sync

rendering DHCP files
Exception occured: <type 'exceptions.KeyError'>
Exception value: 'bond1.11'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 82, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 181, in runner
    return self.remote.api.sync(self.options.get("verbose",False),logger=self.logger)
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 763, in sync
    return sync.run()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 122, in run
    self.write_dhcp()
   File "/usr/lib/python2.7/site-packages/cobbler/action_sync.py", line 208, in write_dhcp
    self.dhcp.write_dhcp_file()
   File "/usr/lib/python2.7/site-packages/cobbler/modules/manage_isc.py", line 106, in write_dhcp_file
    ding[system.name] = {interface["interface_master"]: []}

!!! TASK FAILED !!!

# Pasting the manage_isc.py below , can't attach as file due to other reasons :(
