### ISSUE TITLE
Failed to restart cobblerd.service: Unit not found

### ISSUE THREAD

**Issue by MohanrajBabu** [cobbler/cobbler#2152]
Hello,

Trying to install Release30 version in CentOS7, but getting "Failed to restart cobblerd.service: Unit not found" on running make webtest.

Python3 is installed in a different location than what given in Makefile. So updated the Makefile as below.

Makefile

```
#
# Setup Makefile to match your environment
#
PYTHON=/usr/local/bin/python3
```

make webtest

```
make restartservices
make[1]: Entering directory `/root/cobbler'
if [ -x /sbin/service ] ; then \
	/sbin/service cobblerd restart; \
	if [ -f /etc/init.d/httpd ] ; then \
		/sbin/service httpd restart; \
	elif [ -f /usr/lib/systemd/system/httpd.service ]; then \
		/bin/systemctl restart httpd.service; \
	else \
		/sbin/service apache2 restart; \
	fi; \
elif [ -x /bin/systemctl ]; then \
	if [ -d /lib/systemd/system/apache2.service.d ]; then \
		/bin/systemctl restart apache2.service; \
	else \
		/bin/systemctl restart httpd.service; \
	fi \
else \
	/usr/sbin/service cobblerd restart; \
	/usr/sbin/service apache2 restart; \
fi
Redirecting to /bin/systemctl restart cobblerd.service
Failed to restart cobblerd.service: Unit not found.
make[1]: Leaving directory `/root/cobbler'
```

How to address this issue?
Thanks,
Mohan

**Comment by SchoolGuy** [comment]
I need to add this to the known issues. We need to deprecate service and use `systemctl` because it it the de facto standard of every distro I know of and cobbler currently supports.

**Comment by SchoolGuy** [comment]
Also the paths look a bit strange...

**Comment by MohanrajBabu** [comment]
Its  CentOS VM with only root user configured.  I have installed python via source. It installed in /usr/local/bin directory instead of /usr/bin/python3.

**Comment by SchoolGuy** [comment]
@MohanrajBabu Thats for `make webtest` fine.

**Comment by SchoolGuy** [comment]
It is meant for testing. Normally you should install cobbler from your package repos.

**Comment by SchoolGuy** [comment]
@MohanrajBabu Was this solved or does the error still exist?

**Comment by MohanrajBabu** [comment]
Hi @SchoolGuy ,

OS: CentOS7
cobbler: release30

Tried to install release30 package from source.
Initially got missing directory `/var/lib/cobbler/collection` error on make install.

Manually created the /var/lib/cobbler/collection and run it again, make install worked fine.

Error on make webtest, still persist.

```
make restartservices
make[1]: Entering directory `/root/cobbler'
if [ -x /sbin/service ] ; then \
	/sbin/service cobblerd restart; \
	if [ -f /etc/init.d/httpd ] ; then \
		/sbin/service httpd restart; \
	elif [ -f /usr/lib/systemd/system/httpd.service ]; then \
		/bin/systemctl restart httpd.service; \
	else \
		/sbin/service apache2 restart; \
	fi; \
elif [ -x /bin/systemctl ]; then \
	if [ -d /lib/systemd/system/apache2.service.d ]; then \
		/bin/systemctl restart apache2.service; \
	else \
		/bin/systemctl restart httpd.service; \
	fi \
else \
	/usr/sbin/service cobblerd restart; \
	/usr/sbin/service apache2 restart; \
fi
Redirecting to /bin/systemctl restart cobblerd.service
Failed to restart cobblerd.service: Unit not found.
make[1]: Leaving directory `/root/cobbler'

```

Thanks,
Mohan

**Comment by SchoolGuy** [comment]
I am trying to work on this in this PR: https://github.com/cobbler/cobbler/pull/2237

**Comment by SchoolGuy** [comment]
@MohanrajBabu Would you mind checking if the provided rpm does fix the error. The `make webtest` I will try to fix at a different place...

**Comment by SchoolGuy** [comment]
Okay I fixed the error with restarting cobblerd now but we now have the problem of how to restart the webserver on different distros...

**Comment by MohanrajBabu** [comment]
hi @SchoolGuy 

cobbler gets installed in below location.
```
[root@localhost cobbler]# which cobbler
/usr/local/bin/cobbler
```

service file has a different path
```
[Service]
ExecStart=/usr/bin/cobblerd -F
ExecStartPost=-/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi
PrivateTmp=yes
KillMode=process
```

unit not found error still coming in centos7.

Thanks,
Mohan
