### ISSUE TITLE
Dynamic inventory script throws xmlrpc.client.ProtocolError: <ProtocolError for cobbler/cobbler_api: 404 Not Found>

### ISSUE THREAD

**Issue by ShrutiChavali** [cobbler/cobbler#2348]
### Version

````paste below
````
Cobbler 2.9.0
  source: b'8010c5d8', b'Mon Feb 18 16:08:42 2019 +0100'
  build time: Wed Feb 20 18:17:47 2019

### Question

I am trying to use dynamic inventory of ansible. Copied the cobber.py script and I am trying to run the command, ./cobbler.py --list. It throws a ProtocolError. 

Any help here or suggestion to run this?

**Comment by opoplawski** [comment]
FWIW - I'm using a modified script.  See https://github.com/ansible/ansible/pull/25926

**Comment by ShrutiChavali** [comment]
Thanks for the script. It would help me a lot. 
I have few issues while using the above script.

1. Error: ModuleNotFoundError: No module named 'ConfigParser' (Not supported by Python3)
--> Changed this module to 'configparser', and it works

2. ModuleNotFoundError: No module named 'xmlrpclib' (Not supported by Python3)
--> Changed this as " import xmlrpc.client as xmlrpclib", and it works

3.   File "/usr/lib64/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'cobbler'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cobbler.py", line 331, in <module>
    CobblerInventory()
  File "./cobbler.py", line 80, in __init__
    self.read_settings()
  File "./cobbler.py", line 158, in read_settings
    self.orderby_keyname = config.get('cobbler', 'orderby_keyname')
  File "/usr/lib64/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'cobbler'

--> I am looking into this currently. Please let me know if you have encountered the above, and if any solution.

Thanks a lot for you help.

**Comment by opoplawski** [comment]
Ah, sorry - I'm using a newer version in production.  I'll try to get you a copy soon...

**Comment by opoplawski** [comment]
I've pushed my latest version to https://github.com/opoplawski/ansible/tree/cobbler/contrib/inventory

I see now that I removed environment variable support and the ability to ignore the config file - hope you weren't counting on that...

**Comment by ShrutiChavali** [comment]
@opoplawski 
Thanks a lot for the revised script.
I tried to use the script you shared. The latest one. But I am missing out on something. Still getting this error:

  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cobbler.py", line 376, in <module>
    CobblerInventory()
  File "./cobbler.py", line 95, in __init__
    self.load_inventory_from_cache()
  File "./cobbler.py", line 344, in load_inventory_from_cache
    cache = open(self.cache_path_inventory, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ansible-cobbler.index'

Not sure what I am missing.

**Comment by opoplawski** [comment]
What is your cobbler.ini file?

**Comment by opoplawski** [comment]
Now provided as an inventory plugin: https://github.com/cobbler/ansible
