### ISSUE TITLE
Why doesn't Cobbler 3.1.2 have esxi7 signatures?

### ISSUE THREAD

**Issue by mpsOxygen** [cobbler/cobbler#2421]
### Version

````paste below
````
Cobbler 3.1.2
  source: ?, ?
  build time: Wed Jul  8 00:00:00 2020

### Question

While on the release notes for Cobbler 3.1.2 (https://cobbler.github.io/blog/2020/05/27/cobbler_3.1.2_released.html) it says esxi7 is added:
Signatures for ESXi 6 and 7 (https://github.com/cobbler/cobbler/pull/2308)

In reality I cannot find the signatures in either my build or the master branch on github. 

[root@lab-provisioning-cobbler ~]# cat /var/lib/cobbler/distro_signatures.json | grep esxi7
[root@lab-provisioning-cobbler ~]# 

Is this a bug or what happened? I can find the signature in branch 28, though.

**Comment by SchoolGuy** [comment]
Yes you are correct. We need to include that also for master... Thanks for mentioning.

**Comment by SchoolGuy** [comment]
There is a PR (https://github.com/cobbler/cobbler/pull/2389) which will close this issue but the one who opened it is not working on it sadly.

**Comment by mpsOxygen** [comment]
Is there anything I can do to help?

**Comment by SchoolGuy** [comment]
Port PR #2308 to master and we are good. That is a "simple" json file which should be easy to understand. The tool to modify that json file is sadly not finished and too unstable to use. However if you are interested to help more I could look what there is to be done to test that tool to make it prod ready.

**Comment by mpsOxygen** [comment]
I tried getting it to run on my system, after some modifications to the distro file I got it to import the distro but it does not copy the boot files to the tftpboot directory or the http directory. I can't tell what or where the actual problem is. :(

**Comment by SchoolGuy** [comment]
Don't worry. I will try today at work and report back here.

**Comment by SchoolGuy** [comment]
#2435 should fix this.

**Comment by SchoolGuy** [comment]
Release 3.2.0 will include this PR.

**Comment by mpsOxygen** [comment]
Import is still failing with:
[root@lab-provisioning-cobbler ~]# cobbler import --name=ESXI70b --breed=vmware --path=/mnt/esxi70b
task started: 2020-11-03_153100_import
task started (id=Media import, time=Tue Nov  3 15:31:00 2020)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=vmware, version=esxi67
running: /usr/bin/file /var/www/cobbler/distro_mirror/ESXI70b/vmware-esx-base-osl.txt
received on stdout: /var/www/cobbler/distro_mirror/ESXI70b/vmware-esx-base-osl.txt: UTF-8 Unicode text, with very long lines, with CRLF, CR line terminators

received on stderr: 
Found a candidate signature: breed=vmware, version=esxi70
running: /usr/bin/file /var/www/cobbler/distro_mirror/ESXI70b/vmware-esx-base-osl.txt
received on stdout: /var/www/cobbler/distro_mirror/ESXI70b/vmware-esx-base-osl.txt: UTF-8 Unicode text, with very long lines, with CRLF, CR line terminators

received on stderr: 
Found a matching signature: breed=vmware, version=esxi70
Adding distros from path /var/www/cobbler/distro_mirror/ESXI70b:
running: /usr/bin/file /var/www/cobbler/distro_mirror/ESXI70b/tools.t00
received on stdout: /var/www/cobbler/distro_mirror/ESXI70b/tools.t00: gzip compressed data, was "tools-light.tar", last modified: Tue Jun  2 05:40:38 2020, from Unix, original size modulo 2^32 206807040

received on stderr: 
Exception occured: <class 'TypeError'>
Exception value: cannot use a string pattern on a bytes-like object
Exception Info:
  File "/usr/lib/python3.8/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.8/site-packages/cobbler/remote.py", line 296, in runner
    self.remote.api.import_tree(

  File "/usr/lib/python3.8/site-packages/cobbler/api.py", line 1489, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 191, in run
    import_walker(self.path, self.distro_adder, distros_added)

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 74, in import_walker
    func(arg, top, names)

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 315, in distro_adder
    adtls.append(self.add_entry(dirname, kernel, initrd))

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 341, in add_entry
    archs = self.learn_arch_from_tree()

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 435, in learn_arch_from_tree
    import_walker(self.path, self.arch_walker, result)

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 74, in import_walker
    func(arg, top, names)

  File "/usr/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 468, in arch_walker
    m = re_krn2.match(line)

!!! TASK FAILED !!!

**Comment by SchoolGuy** [comment]
@mpsOxygen The signatures are there. Let's open a new one for this. This is something different as far as I can see.

**Comment by mpsOxygen** [comment]
Ok, will do!
