### ISSUE TITLE
The requested URL returned error: 500 Internal Server Error

### ISSUE THREAD

**Issue by pbvafer** [cobbler/cobbler#3114]
The requested URL returned error: 500 Internal Server Error
Warning: anaconda: failed to fetch kickstart from `https://192.168.60.10/cblr/svc/op/autoinstall/system/nodo1`

Hi, I have a problem with launching a RHEL8 kickstart from a master PC to a node PC, the indicated URL is not visible from the node to be able to be configured by the Cobbler system, in `/var/lib/tftpboot/pxelinux.cfg/"file_MAC"`.

```
timeout 1
prompt 0
default nodo1
ontimeout nodo1
LABEL nodo1
        MENU LABEL nodo1
        kernel /images/RHEL8-x86_64/vmlinuz
        append initrd=/images/RHEL8-x86_64/initrd.img  kssendmac inst.ks=http://192.168.60.10/cblr/svc/op/autoinstall/system/nodo1
        ipappend 2
```

The inst.ks URL is not accessible and the installation fails at that point.

**Comment by pbvafer** [comment]
This is the output of cobbler sync

task started: 2022-05-24_131738_sync
task started (id=Sync, time=Tue May 24 13:17:38 2022)
running python triggers from /var/lib/cobbler/triggers/task/sync/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/sync/pre/*
shell triggers finished successfully
syncing all
running pre-sync triggers
running python triggers from /var/lib/cobbler/triggers/sync/pre/*
running shell triggers from /var/lib/cobbler/triggers/sync/pre/*
shell triggers finished successfully
cleaning trees
removing: /var/www/cobbler/images/RHEL8-x86_64
Successfully removed "/var/lib/tftpboot/pxelinux.cfg/nodo1"
Successfully removed "/var/lib/tftpboot/pxelinux.cfg/01-e0-d5-5e-f9-30-e3"
Successfully removed "/var/lib/tftpboot/pxelinux.cfg/default"
removing: /var/lib/tftpboot/grub/images
removing: /var/lib/tftpboot/grub/i386-pc
removing: /var/lib/tftpboot/grub/x86_64-efi
Successfully removed "/var/lib/tftpboot/grub/grub.0"
Successfully removed "/var/lib/tftpboot/grub/grubx86.efi"
removing: /var/lib/tftpboot/grub/system
removing: /var/lib/tftpboot/grub/system_link
Successfully removed "/var/lib/tftpboot/grub/grub.cfg"
Successfully removed "/var/lib/tftpboot/grub/local_efi.cfg"
Successfully removed "/var/lib/tftpboot/grub/local_legacy.cfg"
Successfully removed "/var/lib/tftpboot/grub/local_powerpc-ieee1275.cfg"
removing: /var/lib/tftpboot/images/RHEL8-x86_64
Successfully removed "/var/lib/tftpboot/ipxe/default.ipxe"
copying bootloaders
running: ['rsync', '-rpt', '--copy-links', '--exclude=.cobbler_postun_cleanup', '/var/lib/cobbler/loaders/', '/var/lib/tftpboot']
received on stdout: 
received on stderr: 
running: ['rsync', '-rpt', '--copy-links', '--exclude=README.grubconfig', '/var/lib/cobbler/grub_config/', '/var/lib/tftpboot']
received on stdout: 
received on stderr: 
copying distros to tftpboot
copying files for distro: RHEL8-x86_64
trying hardlink /var/www/cobbler/distro_mirror/RHEL8-x86_64/images/pxeboot/vmlinuz -> /var/lib/tftpboot/images/RHEL8-x86_64/vmlinuz
trying hardlink /var/www/cobbler/distro_mirror/RHEL8-x86_64/images/pxeboot/initrd.img -> /var/lib/tftpboot/images/RHEL8-x86_64/initrd.img
copying images
generating PXE configuration files
generating: /var/lib/tftpboot/pxelinux.cfg/nodo1
generating: /var/lib/tftpboot/grub/system/nodo1
generating: /var/lib/tftpboot/pxelinux.cfg/01-e0-d5-5e-f9-30-e3
generating: /var/lib/tftpboot/grub/system/e0:d5:5e:f9:30:e3
Successfully removed "/var/lib/tftpboot/grub/system_link/nodo1"
generating PXE menu structure
copying files for distro: RHEL8-x86_64
trying hardlink /var/www/cobbler/distro_mirror/RHEL8-x86_64/images/pxeboot/vmlinuz -> /var/www/cobbler/images/RHEL8-x86_64/vmlinuz
trying hardlink /var/www/cobbler/distro_mirror/RHEL8-x86_64/images/pxeboot/initrd.img -> /var/www/cobbler/images/RHEL8-x86_64/initrd.img
Writing template files for RHEL8-x86_64
processing boot_files for distro: RHEL8-x86_64
cleaning link caches
running post-sync triggers
running python triggers from /var/lib/cobbler/triggers/sync/post/*
running python trigger cobbler.modules.sync_post_restart_services
running shell triggers from /var/lib/cobbler/triggers/sync/post/*
shell triggers finished successfully
running python triggers from /var/lib/cobbler/triggers/change/*
running python trigger cobbler.modules.scm_track
running python trigger cobbler.modules.managers.genders
running shell triggers from /var/lib/cobbler/triggers/change/*
shell triggers finished successfully
*** TASK COMPLETE ***

**Comment by SchoolGuy** [comment]
@pbvafer Thanks for reporting this bug. Could you please restore the content of the template and fill out the required fields? Otherwise it is next to impossible to give you help. For the sake of readability I would also highly appreciate if you would use of the markdown features like code blocks.

**Comment by pbvafer** [comment]
cd /var/www/cobbler/svc/
[ll
total 8
-rwxr-xr-x. 1 apache apache 4229 mar 11 09:59 services.py

**Comment by pbvafer** [comment]
Oh sorry, this is my first incidence

**Comment by SchoolGuy** [comment]
@pbvafer No problem if you need help just ping me. May I edit your post for you if this is your first time?

**Comment by SchoolGuy** [comment]
So the information that is missing to this bug is the version of Cobbler you are using. The version you can get via `cobbler version` or by getting the version of  package you installed via apt-get or rpm.

We recently did changes to this part of the code (specifically in #3113) and thus the exact version is important.

**Comment by pbvafer** [comment]
Of course, thanks!
Cobbler 3.3.2
  source: ?, ?
  build time: Wed May  4 01:38:10 2022

**Comment by pbvafer** [comment]
Excuse my lack of knowledge, are the changes specified in #3113 supposed to solve my problem?

**Comment by pbvafer** [comment]
I was about to modify the previous messages for clarity and documentation of the error.

**Comment by SchoolGuy** [comment]
Argh I copied the wrong PR. Sorry. The correct PR for this is #2534. So the PR I linked before is not related to this issue.

In regard to your problem. Could it be that this is a duplicate of #2967?

> The workaround is to revert the permissions to the old state and make the files world readable. I am working on a solution in the meantime.

To elaborate: We changed the permissions for some files to read only for `root`. Thus the Apache user can't access the correct files sadly. We corrected that but there is not a new release yet with the already merged bugfix since we are waiting for more bugfixes.

**Comment by pbvafer** [comment]
I think it is very much related to the permissions apache has on the files needed to access the Cobbler created system.

**Comment by pbvafer** [comment]
I think you are absolutely right and it is the same problem as #2967. I will check #2967 better and confirm, thanks!

**Comment by pbvafer** [comment]
With these commands I have managed to get the O.S. launch by pxe to work without giving me 500 Internal Server Error problems:

sudo chmod g+rw /etc/cobbler /etc/cobbler/settings.yaml /etc/cobbler/modules.conf
sudo usermod -aG root apache
sudo systemctl restart httpd cobblerd

**Comment by pbvafer** [comment]
Issues #2967 #3016 and #3114 are the same issue.

**Comment by pbvafer** [comment]
The problem I am encountering now, which is no longer related to this, is a loop in the cobbler installation by pxe. When I have on  `/etc/cobbler/settings.yaml` the parameter` pxe_just_once: true` and in the `ks` file the flag `firstboot --enable`.
I don't know, can you give me some guidance on this?

**Comment by SchoolGuy** [comment]
@pbvafer For this we have the flag `netboot_enabled` on a System. Normally you should utilize the snippet `autoinstall_done` which calls `http://<domain>/cblr/svc/op/nopxe/system/<name>` after the installation has succeeded.

**Comment by SchoolGuy** [comment]
Put it in some kind of "post-instal-script" section. I am not aware how you structured your autoinstallation snippets for your kickstart file.

**Comment by pbvafer** [comment]
It is a ks file for RHEL8:

```
#version=RHEL8
# Disable the firewall
firewall --disabled
# Network boot
url --url="http://192.168.60.10/cblr/links/RHEL8-x86_64/"
# Root password
rootpw --iscrypted 

# Network information
network --bootproto=static --ip=192.168.60.21 --netmask=255.255.255.0 --gateway=192.168.60.1 --nameserver=192.168.60.1,8.8.8.8 --device=enp0s25 --hostname=nodo1-ngl --onboot=on --noipv6 --activate
# Encryption CentOS8/RHEL8
authselect --enableshadow --passalgo=sha512
# Use text install
text
# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8
# Configuracion SElinux
selinux --disabled
# System timezone
timezone Europe/Madrid --isUtc --nontp

zerombr
bootloader --location=mbr --append="biosdevname=0" --boot-drive=sdb --driveorder=sdb
# Partition clearing information
clearpart --initlabel --all --drives=sdb
autopart --type=lvm
# Run the Setup Agent on first boot
firstboot --enable
# Disk configuration section
ignoredisk --only-use=sdb
# Do not configure the X Window System
skipx
sshkey --username=root "ssh-rsa ssh-rsa  root@localhost.localdomain"
user --name="name" --password="psswd"

reboot

%packages
@^server-product-environment
kexec-tools
%end
%addon com_redhat_kdump --enable --reserve-mb='auto'
%end
%anaconda
pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok 
pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
%end
```

**Comment by pbvafer** [comment]
At the end of the file I would put this:
```
%post
$SNIPPET('autoinstall_done')
%en
```d

**Comment by pbvafer** [comment]
I'm having trouble accessing the URL you told me to access `http://<domain>/cblr/svc/op/nopxe/system/<name>`. So when you open `http://<domain>/cblr/svc` in the browser i get a message `no mode specified` and I'm still in the installation loop. I think it is a problem related to this issue.

**Comment by pbvafer** [comment]
`services.py` Does not run properly and does not create the right path for cobbler to do its job.

**Comment by SchoolGuy** [comment]
> At the end of the file I would put this:
> 
> ```
> %post
> $SNIPPET('autoinstall_done')
> %end
> ```

Yes this looks good!

**Comment by SchoolGuy** [comment]
> @SchoolGuy I'm having trouble accessing the URL you told me to access `http://<domain>/cblr/svc/op/nopxe/system/<name>`. So when you open `http://<domain>/cblr/svc` in the browser i get a message `no mode specified` and I'm still in the installation loop. I think it is a problem related to this issue.

So the general endpoint you described is not returning anything. So that behaviour is expected. When you call the exact URL I gave to you, you should get a boolean return value.

**Comment by SchoolGuy** [comment]
> `services.py` Does not run properly and does not create the right path for cobbler to do its job.

Do you have any stacktrace for that? Any instructions on how to reproduce that behaviour?

**Comment by pbvafer** [comment]
![nopxe-navegador](https://user-images.githubusercontent.com/79220152/170649032-d411eba9-c532-4291-8190-59daad52329e.png)

@SchoolGuy You are absolutely right with the URL, sorry it was my ignorance, it is working perfectly.

**Comment by pbvafer** [comment]
This is an assumption as I thought it didn't work, but it is my mistake. Forgive my boldness in saying that. The problem I have right now is that the PC that receives the O.S. via PXE-Cobbler-ks is not able to put the installed O.S. in the first place of the Boot BIOS and wants to reinstall it again and again.

**Comment by SchoolGuy** [comment]
Okay wonderful that we are progressing. No problem, I have such mis-assumptions as well. Happens to all of us.

In regard to the new problem: Could it be that you locked the boot-order in the UEFI/BIOS? Because I am not aware of any mechanism that puts PXE-booting as their first boot-entry. But this is just a wild guess.

**Comment by pbvafer** [comment]
I have PXE Legacy netboot enabled, UEFI is not. Should I change it?

**Comment by SchoolGuy** [comment]
The question was not if PXE Legacy Netboot enabled (btw I strongly would recommend UEFI) but what the order in the UEFI is?

So is it:

- PXE
- Hard Drive
- <Other Boot Options>

or is it:

- Hard Drive
- PXE
- <Other Boot Options>

Because if you set `PXE` as the default options you need to check that Cobbler generates the correct PXE Menu for you that instructs the computer to boot from disk and not into a default profile again.

**Comment by pbvafer** [comment]
For reasons of the ongoing project, the order is 1: PXE 2: Hard Drive.
Well, I want to be able to reinstall when I want with another S.O. for example, if I put 1 Hord Drive, when detecting S.O. it will always start from that one, right?

**Comment by pbvafer** [comment]
In this case, how do I check that the PXE Menu is correct? I don't have much knowledge about this.

**Comment by SchoolGuy** [comment]
Okay good. Since PXE is first in your PXE Menu you should then have an entry called `(local)`. Do you see that when the bootloop appears?

**Comment by pbvafer** [comment]
This?
```
totaltimeout 0
prompt 0
default nodo1
ontimeout nodo1
LABEL nodo1
        MENU LABEL nodo1
        localboot -1
```

**Comment by SchoolGuy** [comment]
Do you have an entry which looks like this?

```
LABEL local
        MENU LABEL (local)
        MENU DEFAULT
        LOCALBOOT -1
```

Because that would ensure that your system PXE boots and then uses the hard drive.

**Comment by pbvafer** [comment]
The initial input with the cobbler system running is this:
```
timeout 1
prompt 0
default nodo1
ontimeout nodo1
LABEL nodo1
        MENU LABEL nodo1
        kernel /images/RHEL8-x86_64/vmlinuz
        append initrd=/images/RHEL8-x86_64/initrd.img  kssendmac inst.ks=http://192.168.60.10/cblr/svc/op/autoinstall/system/nodo1
        ipappend 2

```

**Comment by pbvafer** [comment]
The default file is: 
```
DEFAULT menu
PROMPT 0
MENU TITLE Cobbler | https://cobbler.github.io
TIMEOUT 200
TOTALTIMEOUT 6000
ONTIMEOUT local

LABEL local
        MENU LABEL (local)
        MENU DEFAULT
        LOCALBOOT -1

LABEL RHEL8-Nodo1
        MENU LABEL RHEL8-Nodo1
        kernel /images/RHEL8-x86_64/vmlinuz
        append initrd=/images/RHEL8-x86_64/initrd.img  kssendmac inst.ks=http://192.168.60.10/cblr/svc/op/autoinstall/profile/RHEL8-Nodo1
        ipappend 2
LABEL RHEL8-x86_64
        MENU LABEL RHEL8-x86_64
        kernel /images/RHEL8-x86_64/vmlinuz
        append initrd=/images/RHEL8-x86_64/initrd.img  kssendmac inst.ks=http://192.168.60.10/cblr/svc/op/autoinstall/profile/RHEL8-x86_64
        ipappend 2
MENU end
```

**Comment by SchoolGuy** [comment]
Ahh so you have local only in the default boot. Then what should happen is that once `netboot_enabled` is set to false after the autoinstallation the system specific file should vanish since it is not needed anymore. If that is not the case then we have found a bug or I have a logic error in my head.

**Comment by pbvafer** [comment]
Sorry for the late reply. The system-specific file (mac file) does not disappear, it is rewritten to this:
```
LABEL local
        MENU LABEL (local)
        MENU DEFAULT
        LOCALBOOT -1
```
But it does not boot the system, try DHCP/PXE boot again.

**Comment by pbvafer** [comment]
Even if you delete the mac file by hand, try DHCP/PXE boot again.

**Comment by SchoolGuy** [comment]
Yeah but that is not a problem as long as the localboot entry is set.

**Comment by SchoolGuy** [comment]
So even though you PXE boot the PC should boot from the disk.

**Comment by pbvafer** [comment]
Should I change the -1 of localboot to the appropriate value?

**Comment by pbvafer** [comment]
I don't have the dhcp-server configured in cobbler, as I have it in a router.

**Comment by SchoolGuy** [comment]
No that should be correct.

**Comment by SchoolGuy** [comment]
What does the system actually do when this bootentry is used?

**Comment by SchoolGuy** [comment]
Yeah and then?

**Comment by pbvafer** [comment]
On the newly installed PC nothing, a flashing '-' remains.

**Comment by pbvafer** [comment]
But if I go to the BIOS/UEFI and change the boot order to the O.S. I just installed, it boots.

**Comment by SchoolGuy** [comment]
Okay that is interesting. So from Cobbler side I believe everything works. I am not aware of what to improve. The things you mentioned are looking fine.

**Comment by pbvafer** [comment]
The RHEL8 image I am injecting is x86_64. 
```
bootloaders_formats:
  x86_64-efi:
    binary_name: grubx86.efi
    extra_modules: [chain, efinet]
```
Dónde debería estar el fichero de boot `grubx86.efi`?

**Comment by SchoolGuy** [comment]
@pbvafer Both of that statements should work as expected. I still don't see the problem that is causing the trouble. Sorry... :/

**Comment by pbvafer** [comment]
One doubt I have, if I already have a DCHP-Server external to Cobbler, I should not install the dhcp-server package nor modify the `dhcp.template` file in `/etc/cobbler`, right?

**Comment by pbvafer** [comment]
In dhcp.template in the pxe options, there is no `grubx86.efi `option:
```
class "pxeclients" {
          match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";

          # Legacy
          if option system-arch = 00:00 {
              filename "grub/grub.0";
          }
          # UEFI-32-1
          if option system-arch = 00:06 {
               # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
          # UEFI-32-2
          if option system-arch = 00:02 {
              # Not supported, no 32 bit UEFI grub executable
              filename "unsupported";
          }
          # UEFI-64-1
          else if option system-arch = 00:07 {
              filename "grub/grubx64.efi";
          }
          # UEFI-64-2
          else if option system-arch = 00:08 {
              filename "grub/grubx64.efi";
          }
          # UEFI-64-3
          else if option system-arch = 00:09 {
              filename "grub/grubx64.efi";
          }
          # armv7   (aka arm 32 bit)
          else if option system-arch = 00:0a {
              filename "grub/armv7.efi";
          }
          # aarch64 (aka arm 64 bit)
          else if option system-arch = 00:0b {
              filename "grub/grubaa64.efi";
          }
          # RiskV 32 bit
          else if option system-arch = 00:25 {
              #ToDo petitboot loader
              # petitboot should support pxelinux config files
              filename "unsupported";
          }
          #RiskV 32 bit
          else if option system-arch = 00:27 {
              #ToDo petitboot loader
              # petitboot should support pxelinux config files
              filename "unsupported";
          }
          else if option system-arch = 00:0e {
              # FIXME add petitboot support for ppc64(le)
              filename "grub/grub.ppc64le";
          }
          else
          {
              filename "grub/grub.0";
          }
}

```

**Comment by SchoolGuy** [comment]
The template in `/etc/cobbler` you can edit for sure. That is why we have a template. However you obviously need to maintain the template. If you don't want to use the DHCP from Cobbler that is totally fine but that means you are responsible to set the correct filename.

**Comment by pbvafer** [comment]
Yes, but my question is if I still don't use Cobbler DHCP I have to edit the `dhcp.template`?

**Comment by SchoolGuy** [comment]
No that you don't need to do.

**Comment by pbvafer** [comment]
Thank you for getting involved in my problem, you have helped me a lot. If I solve this I will let you know, greetings!

**Comment by pbvafer** [comment]
@SchoolGuy One more question, is it ok that the `autoinstall_done` file in `/var/lib/cobbler/snippets` is all commented out, maybe that's why it's not working for me?

**Comment by SchoolGuy** [comment]
If you want to use Jinja2 that is also possible but that required deeper understanding of Cobbler and its templating system.

**Comment by pbvafer** [comment]
Ok, thanks!

**Comment by SchoolGuy** [comment]
Are all your problems resolved at the moment? If yes I would like to close this issue. If you have further additional questions, I would love if you open a GitHub Discussion in the Q&A section. :)

**Comment by pbvafer** [comment]
OK, I still have the same problem but I understand that it is no longer to do with the original Issue or Cobbler. Thanks!

**Comment by SchoolGuy** [comment]
@pbvafer Feel free to open the topic as a GitHub Discussion. However since this issue is done I will close it now. :)
