### ISSUE TITLE
Network EFI boot failure if cobbler is running on CentOS 9

### ISSUE THREAD

**Issue by bruncsak** [cobbler/cobbler#3815]
### Describe the bug

If the host operating system is CentOS 9 for the cobbler server, EFI network boot is failing.
It is not a bug with cobbler as such, but I feel it is a good place to document.
It is rather an incompatibility.

In April 2024, EFI network boot was working.
An example, the following system specific file was successfully uploaded via TFTP (from the tftp log):
`finished grub/system/00:1d:d8:b7:21:0d`

In August 2024 it is failing.
The loader was looking for the file `/EFI/centos/system/00:50:56:a8:b9:4d` (from the tftp log as well)

It looks like the `grubx64.efi` file shiped by the OS was updated, and the a kind of default prefix is changed from `grub/system` to `EFI/centos/system`. 

rpm kit upgrade list:

````
2024-05-07T12:26:47+0200 SUBDEBUG Upgrade: grub2-efi-x64-1:2.06-78.el9.x86_64
2024-05-07T12:26:48+0200 SUBDEBUG Upgraded: grub2-efi-x64-1:2.06-68.el9.x86_64
2024-06-12T07:52:39+0200 SUBDEBUG Upgrade: grub2-efi-x64-1:2.06-80.el9.x86_64
2024-06-12T07:52:43+0200 SUBDEBUG Upgraded: grub2-efi-x64-1:2.06-78.el9.x86_64
2024-07-04T08:42:20+0200 SUBDEBUG Upgrade: grub2-efi-x64-1:2.06-82.el9.x86_64
2024-07-04T08:42:21+0200 SUBDEBUG Upgraded: grub2-efi-x64-1:2.06-80.el9.x86_64
````
### Cobbler version

cobbler-3.3.4

### Operating system

CentOS 9

### Additional detail

As a workaround, the following commands after `cobbler sync` was helping to successfully EFI network boot:
````
mkdir -p /var/lib/tftpboot/EFI/centos
ln -s ../../grub/system /var/lib/tftpboot/EFI/centos/
````

**Comment by uebian** [comment]
#3789 should fix the issue.

**Comment by bruncsak** [comment]
No, [#3789 ](https://github.com/cobbler/cobbler/pull/3789) does not solve the issue, I just tested.
